name: CI/CD Python Application

on:
 push:
 workflow_dispatch:

jobs:
 ci-cd:
  runs-on: ubuntu-latest
  env:
   DOCKER_IMAGE: karthikamn/flask-api-python-app-lbg
   
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4.2.2
 
    - name: Login to Docker
      uses: docker/login-action@v3.3.0
      with:
       username: ${{secrets.DOCKER_USERNAME1}}
       password: ${{secrets.DOCKER_PASSWORD1}}
   
    - name: Build docker image
      run: |
       docker build -t $DOCKER_IMAGE:${{github.sha}} .
       docker tag $DOCKER_IMAGE:${{github.sha}} $DOCKER_IMAGE:v1.1
       
    - name: Push docker image
      run: |
       docker push $DOCKER_IMAGE:${{github.sha}}
       docker push $DOCKER_IMAGE:v1.1

   
      
       
       
      
   
        
          
       
       
       
        
      
